version: 2.1

executors:
  meetup:
    docker:
      # Main image to be used within this configuration
      - image: circleci/node:12.14.1
        environment: # environment variables for database
          NODE_ENV: test
          TEST_DB_USERNAME: postgres
          TEST_DB_PASSWORD: ''
          TEST_DB_NAME: test
          TEST_DB_HOST: localhost
          CC_TEST_REPORTER_ID: '33e03ba664eb080fb17061b2eea9bd2a29b84d9dc4f3ac20de697a94195be6b9'
          JWT_PRIVATE_KEY: henry

      # Environment variables for database
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''

jobs:
  test:
    executor: meetup
    steps:
      - checkout
      - run: sudo npm install
      - save_cache:
          key: disposables-cache-1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run: ./node_modules/.bin/sequelize db:migrate
      - run: ./cc-test-reporter before-build
      - run: npm test
      - run: ./cc-test-reporter format-coverage -t lcov --prefix tmp/
      - run: ./cc-test-reporter after-build -t lcov --exit-code $?
      - run: npm run coveralls

workflows:
  'Run tests':
    jobs:
      - test
